version: "3.8"

x-custom:
  app:
    - &rails_env "development"
  postgres:
    - &postgres_user "${DATABASE_USERNAME:-postgres}"
    - &postgres_password "${DATABASE_PASSWORD:-password}"

services:
  app:
    image: decidim-cfj
    command: supervisorctl start rails
    build:
      context: ./
      args:
        RAILS_ENV: *rails_env
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      # exclude volumes
      - /app/vendor
      - /app/tmp
      - /app/log
      - /app/.git
    environment:
      PORT: 3000
      DATABASE_HOST: pg
      DATABASE_USERNAME: *postgres_user
      DATABASE_PASSWORD: *postgres_password
      RAILS_ENV: *rails_env
    ports:
      - 3000:3000
    links:
      - pg
  pg:
    image: postgres:12
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: *postgres_user
      POSTGRES_PASSWORD: *postgres_password
    ports:
      - 5433:5432

volumes:
  node_modules: {}
  pg-data: {}
